# インストール先の指定
cask_args appdir: "/Applications"

# 外部ライブラリをインストール
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "trendyol/trendyol-tap"
tap "wez/wezterm"

# CLIアプリ
brew "bat"
brew "diff-so-fancy"
brew "direnv"
brew "dust"
brew "fzf"
brew "ghq"
brew "git"
brew "git-delta"
brew "gitui"
brew "ncurses"
brew "htop"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lolcat"
brew "neovim"
brew "node"
brew "nodenv"
brew "prettyping"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "tealdeer"
brew "tig"
brew "tmux"
brew "tokei"
brew "tree"
brew "xsv"
brew "zoxide"

# GUIアプリ
cask "google-chrome"
cask "docker"
cask "font-hack-nerd-font"
cask "wezterm"
cask "postman"
cask "warp"
